services:
  backend:
    build:
      context: ./balance-backend
    restart: unless-stopped
    environment:
      PORT: 5050
      MONGO_URI: mongodb+srv://shehrozsafarish_db_user:KAbdmrB894fzNZ7t@cluster0.pbadlab.mongodb.net/smart_scheduler?retryWrites=true&w=majority&appName=Cluster0
      JWT_SECRET: change_this_to_a_long_random_string
      JWT_EXPIRES_IN: 7d
      CORS_ORIGIN: http://localhost:5173
      OPENAI_API_KEY: ${OPENAI_API_KEY}
    ports:
      - "5050:5050"

  frontend:
    build:
      context: ./smart-scheduler-frontend
      args:
        VITE_API_URL: http://localhost:5050/api
    restart: unless-stopped
    depends_on:
      - backend
    ports:
      - "4173:4173"
